name: desihigh
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas
  - astropy
  - scipy
  - ipympl
  - jupyter
  - notebook
  - pip:
    - git+https://github.com/DESIHIGH/desihigh.git
