# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/osx-64/ca-certificates-2020.6.24-0.conda
https://repo.anaconda.com/pkgs/main/osx-64/intel-openmp-2019.4-233.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcxx-10.0.0-1.conda
https://repo.anaconda.com/pkgs/main/osx-64/libgfortran-3.0.1-h93005f0_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/xz-5.2.5-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zlib-1.2.11-h1de35cc_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/libffi-3.3-hb1e8313_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libpng-1.6.37-ha441bb4_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-2019.4-233.conda
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.2-h0a44026_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/openssl-1.1.1g-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tk-8.6.10-hb0a8c7a_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/freetype-2.10.2-ha233b18_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libedit-3.1.20191231-haf1e3a3_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/readline-8.0-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/sqlite-3.32.3-hffcf06c_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/python-3.8.3-h26836e1_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/certifi-2020.6.20-py38_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/kiwisolver-1.2.0-py38h04f5b5a_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pytz-2020.1-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.15.0-py_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tornado-6.0.4-py38h1de35cc_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/cycler-0.10.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-service-2.3.0-py38hfbe908c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-py_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-47.3.1-py38_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.18.5-py38h3304bdc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/wheel-0.34.2-py38_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pip-20.1.1-py38_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-3.2.2-0.conda
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-base-3.2.2-py38h5670ca0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl_fft-1.1.0-py38hc64f4ea_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl_random-1.1.1-py38h959d312_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.18.5-py38h1da2735_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pandas-1.0.5-py38h959d312_0.conda
